<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6ba69cce-be12-46e0-92de-2845f50b8dfd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0" />
  </ItemGroup>

</Project>
